server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: practice-makes-perfect

# 日志配置
logging:
  level:
    root: INFO
    com.practice.pmp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

